#!/bin/sh

echo "*********************************************************"
echo "*                                                       *"
echo "* XStreamity                                           *"
echo "* by KiddaC (c) 2020                                    *"
echo "*                                                       *"
echo "* Restart Enigma-2 GUI to add plugin into plugin list   *"
echo "*********************************************************"
sleep 5
exit 0
